name: gully_app
description: A new Flutter project.
publish_to: "none"

version: 1.1.0+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  get: ^5.0.0-release-candidate-4
  pin_code_fields: ^8.0.1
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  device_preview: ^1.1.0
  logger: ^2.0.1
  firebase_auth: ^4.8.0
  google_sign_in: ^6.1.4
  firebase_core: ^2.15.1
  json_annotation: ^4.8.1
  intl: ^0.18.1
  image_picker: ^1.0.5
  google_maps_flutter: ^2.5.0
  google_places_flutter: ^2.0.6
  mime: ^1.0.4
  http: ^1.2.1
  permission_handler: ^11.0.1
  geolocator: ^12.0.0
  cached_network_image: ^3.3.1
  geocoding: ^2.1.1
  socket_io_client: ^2.0.3+1
  flutter_widget_from_html: ^0.14.11
  firebase_messaging: ^14.7.10
  get_storage: ^2.1.1
  flutter_native_contact_picker: ^0.0.6
  flutter_cache_manager: ^3.3.1
  restart_app: ^1.2.1
  carousel_slider: ^4.2.1
  url_launcher: ^6.2.5
  firebase_crashlytics: ^3.4.18
  share_plus: ^7.2.2
  package_info_plus: ^6.0.0
  app_links: ^4.0.1
  connectivity_widget: ^2.0.0
  flutter_localizations:
    sdk: flutter
  razorpay_flutter: ^1.3.0
  flutter_media_downloader: ^1.0.4
  # connectivity_plus: ^6.0.1

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/.
  fonts:
    - family: Gotham
      fonts:
        - asset: assets/fonts/Gotham-Black.otf
          weight: 700
        - asset: assets/fonts/Gotham-Bold.otf
          weight: 600
        - asset: assets/fonts/GothamMedium.ttf
          weight: 500
        - asset: assets/fonts/Gotham-Light.otf
          weight: 300
        - asset: assets/fonts/Gotham-Thin.otf
          weight: 100
